### ISSUE TITLE
Is there any way to make icon edges stick to pixels?

### ISSUE THREAD

**Issue by FinesseRus** [nfroidure/svgicons2svgfont#78]
I have an SVG icon which has the size 17x17px and is designed to be pixel-perfect. This is how it looks in an editor:

![2017-10-14 12 30 15](https://user-images.githubusercontent.com/9006227/31571833-5e83a0d8-b0dd-11e7-9009-854da4f0a1ec.png)

When I convert the icon to an SVG font and insert the icon to a HTML page (the icon has CSS style `font-size: 17px;`), the icon edges become blurred:

![2017-10-14 12 26 04](https://user-images.githubusercontent.com/9006227/31571849-e2f225ba-b0dd-11e7-9ce1-d67a0b8ec467.png)

Is there any way to make the icon edges be sharp and crispy in the font?

**Comment by NaridaL** [comment]
how are you inserting in into the HTML?

**Comment by FinesseRus** [comment]
@NaridaL First I make a font file using svgicons2svgfont.

Then I add a font-face rule to a CSS file:

```css
@font-face {
    font-family: 'icons';
    src: url("../fonts/icons.svg") format('svg');
    font-weight: normal;
    font-style: normal;
}
```

Then describe the icons in the CSS file:

```css
.icon {
    line-height: 1;
}
.icon:before {
    font-family: 'icons';
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-style: normal;
    font-variant: normal;
    font-weight: normal;
    text-decoration: none;
    text-transform: none;
    display: inline-block;
    vertical-align: bottom;
}
.icon__4squares:before {
    content: "\E001"
}
```

And add an icon to a HTML code:

```html
<i class="icon icon__4squares"></i>
```
